database:
  enabled-stats: false

bungee:
  bungee-mode: false
  on-leave: JOIN_SERVER
  lobby-server: hub
  leave-commands:
    - "custom command %player%"
    - "custom command2"

cooldown: 1
waiting-time: 40
full-waiting-time: 10
ending-time: 10
use-main-lobby: true
auto-join-on-end: true
date-format: "yyyy-MM-dd"
time-format: "mm:ss"


items:
  leave-item:
    type: CLOCK
    slot: 8

sounds:
  join:
    enabled: true
    sound: ENTITY_ENDERMAN_TELEPORT
    volume: 1
    pitch: 1
  leave:
    enabled: true
    sound: ENTITY_ENDERMAN_TELEPORT
    volume: 1
    pitch: 1
  click:
    enabled: true
    sound: UI_BUTTON_CLICK
    volume: 1
    pitch: 1
  countdown:
    enabled: true
    sound: BLOCK_NOTE_BLOCK_PLING
    volume: 100
  start:
    enabled: true
    sound: ENTITY_ENDER_DRAGON_GROWL
    volume: 100
    pitch: 1
  win:
    enabled: true
    sound: ENTITY_ENDER_DRAGON_DEATH
    volume: 100
    pitch: 1
  defeat:
    enabled: true
    sound: ENTITY_WITHER_SPAWN
    volume: 100
    pitch: 1


particles:
  join:
    enabled: true
    particle: CLOUD
    count: 50
    offset: 1
    speed: 0.1
  leave:
    enabled: true
    particle: CLOUD
    count: 50
    offset: 1
    speed: 0.1
  win:
    enabled: true
    particle: HEART
    count: 30
    offset: 0.5
    speed: 0.1

color-signs: true
sign-colors:
  inactive: BLACK_STAINED_GLASS
  waiting: LIME_STAINED_GLASS
  starting: CYAN_STAINED_GLASS
  game: RED_STAINED_GLASS
  ending: PURPLE_STAINED_GLASS

command-blocker: BLACKLIST
command-blocker-list:
  - me
  - spawn
win-rewards-enabled: true
win-rewards:
  1:
    - eco give %player% 100
  2:
    - eco give %player% 50
  3:
    - eco give %player% 25
